name: Bug/Crash Report
description: Create a bug or crash report for doiksub.
labels: [bug]
title: "[Bug] <title>"

body:
    - type: markdown
      attributes:
          value: |
              GitHub Issues are for development, not support!

              If you are experiencing any of the following issues, ask in our [Discord server](https://discord.gg/98MCTbfDgC) for support:
              - doiksub doesn't work or crashes
              - A plugin doesn't work anymore
              - You are having issues installing doiksub
              - You want to ask a question about doiksub or one of its plugins

    - type: textarea
      id: bug-description
      attributes:
          label: What happens when the bug or crash occurs?
          description: Where does this bug or crash occur, when does it occur, etc.
          placeholder: The bug/crash happens sometimes when I do ..., causing this to not work/the app to crash. I think it happens because of ... / I'm unsure why it might happen.
      validations:
          required: true

    - type: textarea
      id: expected-behaviour
      attributes:
          label: What is the expected behaviour?
          description: Simply detail what the expected behaviour is.
          placeholder: I expect Discord to open the ... page instead of ..., it prevents me from doing ...
      validations:
          required: true

    - type: textarea
      id: steps-to-take
      attributes:
          label: How do you recreate this bug or crash?
          description: Give us a list of steps in order to recreate the bug or crash.
          placeholder: |
              1. Do ...
              2. Then ...
              3. Do this ..., ... and then ...
              4. Observe "the bug" or "the crash"
      validations:
          required: true

    - type: textarea
      id: crash-log
      attributes:
          label: Errors (optional, does very much so help)
          description: Open the Developer Console with `Ctrl+Shift+i` / `Cmd+Option+i`. Then look for any red errors (Ignore network errors like Failed to load resource) and paste them between the "```".
          value: |
              ```
              Replace this text with your crash-log.
              ```
      validations:
          required: false

    - type: checkboxes
      id: agreement-check
      attributes:
          label: Request Agreement
          options:
              - label: I've searched existing issues and this hasn't been reported before
              - label: I built doiksub from source (or use an official release of this fork), not some random repack
              - label: This is not a support request
